trigger:
  branches:
    include:
      - "master"
      - "*.x"
  tags:
    include:
      - "*"

jobs:
- job: 'windows'
  pool:
    vmImage: 'windows-2019'
  container: $[variables.containerImage]
  strategy:
    matrix:
      Python38-x86_64:
        TOXENV: py38
        containerImage: 'pyca/cryptography-runner-windows:py3-x86_64'
        PYTHON_DIR: 'Python38'
        SODIUM_LIB_PATH: 'C:/libsodium/x64/Release/v140/static'
  steps:
  - powershell: |
      $url = "https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-msvc.zip"
      $sha256hash = "C1D48D85C9361E350931FFE5067559CD7405A697C655D26955FB568D1084A5F4"
      Write-Host ('Downloading {0} ...' -f $url)
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      # See https://github.com/PowerShell/PowerShell/issues/2138
      $ProgressPreference = 'SilentlyContinue'
      Invoke-WebRequest -Uri $url -OutFile 'libsodium.zip'
      if ((Get-FileHash libsodium.zip -Algorithm "SHA256").Hash -ne $sha256hash) {
        exit 1
      }
      Expand-Archive libsodium.zip -DestinationPath c:\
    displayName: 'Download libsodium libraries'
  - powershell: |
      Copy-Item ".azure-pipelines/windows/stdint.h" -Destination "C:/libsodium/include/stdint.h"
    displayName: 'Copy stdint.h to include dir (distant weeping)'
  - script: C:/%PYTHON_DIR%/Scripts/pip install codecov
    displayName: 'Install codecov'
  - script: |
        set PYNACL_SODIUM_LIBRARY_NAME=sodium
        set PYNACL_SODIUM_STATIC=1
        set SODIUM_INSTALL=system
        set INCLUDE=C:/libsodium/include;%INCLUDE%
        set LIB=%SODIUM_LIB_PATH%;%LIB%
        C:/%PYTHON_DIR%/Scripts/tox
        IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%
    displayName: 'Run tests'
  - script: set PATH=%PATH%;C:/%PYTHON_DIR%/Scripts; & codecov -e AGENT_OS,TOXENV,WINDOWS_ARCH
    displayName: 'Submit coverage'
    condition: succeeded()
