trigger: none
pr: none

jobs:
    - job: 'windows'
      pool:
          vmImage: 'windows-2019'
      container: $[variables.containerImage]
      strategy:
          matrix:
              Python38-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py3-x86_64'
                  SODIUM_LIB_PATH: 'C:/libsodium/x64/Release/v140/static'
                  PYTHON_VERSION: '38'
                  WINDOWS_ARCH: 'x86_64'
      steps:
          - powershell: |
              $url = "https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-msvc.zip"
              $sha256hash = "C1D48D85C9361E350931FFE5067559CD7405A697C655D26955FB568D1084A5F4"
              Write-Host ('Downloading {0} ...' -f $url)
              [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
              # See https://github.com/PowerShell/PowerShell/issues/2138
              $ProgressPreference = 'SilentlyContinue'
              Invoke-WebRequest -Uri $url -OutFile 'libsodium.zip'
              if ((Get-FileHash libsodium.zip -Algorithm "SHA256").Hash -ne $sha256hash) {
                exit 1
              }
              Expand-Archive libsodium.zip -DestinationPath c:\
            displayName: 'Download libsodium libraries'
          - powershell: |
              Copy-Item ".azure-pipelines/windows/stdint.h" -Destination "C:/libsodium/include/stdint.h"
            displayName: 'Copy stdint.h to include dir (distant weeping)'
          - script: '"C:/Python%PYTHON_VERSION%/Scripts/pip" install wheel cffi six'
            displayName: Install wheel and our Python dependencies
          - script: |
              set PYNACL_SODIUM_LIBRARY_NAME=sodium
              set PYNACL_SODIUM_STATIC=1
              set SODIUM_INSTALL=system
              set INCLUDE=C:/libsodium/include;%INCLUDE%
              set LIB=%SODIUM_LIB_PATH%;%LIB%
              C:/Python%PYTHON_VERSION%/Scripts/pip wheel pynacl --no-use-pep517 --wheel-dir=wheelhouse --no-binary pynacl
            displayName: Build the wheel
          - script: '"C:/Python%PYTHON_VERSION%/Scripts/pip" install -f wheelhouse pynacl --no-index'
            displayName: Test installing the wheel
          - script: |
              "C:/Python%PYTHON_VERSION%/python" -c "import nacl.signing; key = nacl.signing.SigningKey.generate();signature = key.sign(b'test'); key.verify_key.verify(signature)"
            displayName: Test the installed wheel
          - script: mkdir pynacl-wheelhouse
            displayName: Create a directory for placing the final wheel in
          - script: move wheelhouse\pynacl*.whl pynacl-wheelhouse\
            displayName: Move the pynacl wheel into the final wheel house
          - task: PublishBuildArtifacts@1
            inputs:
                pathToPublish: pynacl-wheelhouse/
                artifactName: pynacl-windows-$(WINDOWS_ARCH)-python$(PYTHON_VERSION)
